# Generated by Django 3.1.7 on 2022-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildocumentmonitoring',
            name='email_status',
            field=models.PositiveIntegerField(db_column='EMAIL_STATUS'),
        ),
        migrations.AlterField(
            model_name='emailusermonitoring',
            name='email_status',
            field=models.PositiveIntegerField(db_column='EMAIL_STATUS'),
        ),
    ]
