# Generated by Django 3.1.7 on 2022-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Shopping_Cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scitem',
            old_name='good_marking',
            new_name='goods_marking',
        ),
        migrations.AlterField(
            model_name='scitem',
            name='ship_from_addr_num',
            field=models.CharField(blank=True, db_column='SHIP_FROM_ADDR_NUM', max_length=10, null=True, verbose_name='ship from addr num'),
        ),
    ]
