# Generated by Django 3.1.7 on 2022-06-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Shopping_Cart', '0002_auto_20220531_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaddresses',
            name='fax_number',
            field=models.CharField(blank=True, db_column='FAX_NUMBER', max_length=30, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='scaddresses',
            name='title',
            field=models.CharField(db_column='TITLE', max_length=40, null=True),
        ),
    ]
