# Generated by Django 3.1.7 on 2022-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Shopping_Cart', '0003_auto_20220620_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scitem',
            name='asn_ind',
            field=models.BooleanField(db_column='ASN_IND', default=False, null=True, verbose_name='Advance shipment Notice'),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='fin_entry_ind',
            field=models.BooleanField(blank=True, db_column='FIN_ENTRY_IND', default=False, null=True, verbose_name='Fin entry ind'),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='gr_ind',
            field=models.BooleanField(db_column='GR_IND', default=False, null=True, verbose_name='Gr ind'),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='gr_ind_limi',
            field=models.BooleanField(db_column='GR_IND_LIMI', default=False, null=True, verbose_name='Gr ind'),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='ir_gr_ind',
            field=models.BooleanField(db_column='IR_GR_IND', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='ir_gr_ind_limi',
            field=models.BooleanField(db_column='IR_GR_IND_LIMI', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='ir_ind',
            field=models.BooleanField(db_column='IR_IND', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='offcatalog',
            field=models.BooleanField(blank=True, db_column='OFFCATALOG', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scitem',
            name='po_resp',
            field=models.BooleanField(db_column='PO_RESP', default=False, null=True, verbose_name='PO Response'),
        ),
    ]
