# Generated by Django 3.1.7 on 2022-05-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Chat', '0001_initial'),
        ('eProc_Configuration', '0002_auto_20220519_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipants',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='chatparticipants',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE_ID', max_length=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='chatcontent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
    ]
