# Generated by Django 3.1.7 on 2022-05-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Shopping_Cart', '0001_initial'),
        ('eProc_Chat', '0002_auto_20220519_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='sc_header_guid',
            field=models.ForeignKey(blank=True, db_column='SC_HEADER_GUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Shopping_Cart.scheader'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipants',
            unique_together={('room_no', 'client', 'username', 'chat_type')},
        ),
    ]
