# Generated by Django 3.1.7 on 2022-05-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Configuration', '0002_auto_20220519_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='EformData',
            fields=[
                ('cart_guid', models.CharField(db_column='CART_GUID', max_length=32, primary_key=True, serialize=False)),
                ('form_field1', models.CharField(blank=True, db_column='FORM_FIELD1', max_length=50, null=True)),
                ('form_field2', models.CharField(blank=True, db_column='FORM_FIELD2', max_length=50, null=True)),
                ('form_field3', models.CharField(blank=True, db_column='FORM_FIELD3', max_length=50, null=True)),
                ('form_field4', models.CharField(blank=True, db_column='FORM_FIELD4', max_length=50, null=True)),
                ('form_field5', models.CharField(blank=True, db_column='FORM_FIELD5', max_length=50, null=True)),
                ('form_field6', models.CharField(blank=True, db_column='FORM_FIELD6', max_length=50, null=True)),
                ('form_field7', models.CharField(blank=True, db_column='FORM_FIELD7', max_length=50, null=True)),
                ('form_field8', models.CharField(blank=True, db_column='FORM_FIELD8', max_length=50, null=True)),
                ('form_field9', models.CharField(blank=True, db_column='FORM_FIELD9', max_length=50, null=True)),
                ('form_field10', models.CharField(blank=True, db_column='FORM_FIELD10', max_length=50, null=True)),
                ('item_num', models.PositiveIntegerField(db_column='ITEM_NUM', null=True, verbose_name='Item Number')),
                ('eform_data_created_at', models.DateTimeField(db_column='EFORM_DATA_CREATED_AT', null=True)),
                ('eform_data_created_by', models.CharField(db_column='EFORM_DATA_CREATED_BY', max_length=12, null=True)),
                ('eform_data_changed_at', models.DateTimeField(blank=True, db_column='EFORM_DATA_CHANGED_AT', null=True)),
                ('eform_data_changed_by', models.CharField(db_column='EFORM_DATA_CHANGED_BY', max_length=12, null=True)),
                ('eform_data_source_system', models.CharField(db_column='eform_data_source_system', max_length=20)),
                ('eform_data_destination_system', models.CharField(db_column='EFORM_DATA_DESTINATION_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'MTD_EFORM',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EformFieldData',
            fields=[
                ('eform_field_data_guid', models.CharField(db_column='EFORM_FIELD_DATA_GUID', max_length=40, primary_key=True, serialize=False)),
                ('cart_guid', models.CharField(db_column='CART_GUID', max_length=32, null=True)),
                ('favourite_cart_guid', models.CharField(db_column='FAVOURITE_CART_GUID', max_length=32, null=True)),
                ('eform_id', models.CharField(db_column='EFORM_ID', max_length=40, null=True)),
                ('eform_type', models.CharField(db_column='EFORM_TYPE', max_length=40)),
                ('eform_field_name', models.CharField(db_column='EFORM_FIELD_NAME', max_length=200, null=True)),
                ('eform_field_data', models.CharField(db_column='EFORM_FIELD_DATA', max_length=1000, null=True)),
                ('eform_field_count', models.PositiveIntegerField(db_column='EFORM_FIELD_COUNT', null=True)),
                ('eform_field_data_created_at', models.DateTimeField(db_column='EFORM_FIELD_DATA_CREATED_AT', null=True)),
                ('eform_field_data_created_by', models.CharField(db_column='EFORM_FIELD_DATA_CREATED_BY', max_length=12, null=True)),
                ('eform_field_data_changed_at', models.DateTimeField(blank=True, db_column='EFORM_FIELD_DATA_CHANGED_AT', null=True)),
                ('eform_field_data_changed_by', models.CharField(db_column='EFORM_FIELD_DATA_CHANGED_BY', max_length=12, null=True)),
                ('eform_field_data_source_system', models.CharField(db_column='EFORM_FIELD_DATA_SOURCE_SYSTEM', max_length=20)),
                ('eform_field_data_destination_system', models.CharField(db_column='EFORM_FIELD_DATA_DESTINATION_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MTD_EFORM_FIELD_DATA',
                'managed': True,
            },
        ),
    ]
