# Generated by Django 3.1.7 on 2022-05-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Form_Builder', '0001_initial'),
        ('eProc_Shopping_Cart', '0001_initial'),
        ('eProc_Configuration', '0002_auto_20220519_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='eformfielddata',
            name='item_guid',
            field=models.ForeignKey(db_column='ITEM_GUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Shopping_Cart.scitem'),
        ),
        migrations.AddField(
            model_name='eformfielddata',
            name='product_eform_pricing_guid',
            field=models.ForeignKey(db_column='product_eform_pricing_guid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.producteformpricing'),
        ),
        migrations.AddField(
            model_name='eformdata',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='eformdata',
            name='form_id',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.freetextform'),
        ),
        migrations.AddField(
            model_name='eformdata',
            name='item_guid',
            field=models.ForeignKey(db_column='ITEM_GUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Shopping_Cart.scitem'),
        ),
    ]
