# Generated by Django 3.1.7 on 2022-10-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Form_Builder', '0003_eformfielddata_po_item_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eformfielddata',
            name='price',
            field=models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='eformfielddata',
            name='price_unit',
            field=models.CharField(db_column='PRICE_UNIT', default='1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='eformfielddata',
            name='pricing_type',
            field=models.CharField(db_column='PRICING_TYPE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eformfielddata',
            name='product_description',
            field=models.CharField(db_column='PRODUCT_DESCRIPTION', max_length=500, null=True, verbose_name='Product Short Description'),
        ),
    ]
