# Generated by Django 3.1.7 on 2022-10-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Form_Builder', '0004_auto_20221025_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eformfielddata',
            name='price',
        ),
        migrations.RemoveField(
            model_name='eformfielddata',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='eformfielddata',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='eformfielddata',
            name='product_description',
        ),
    ]
