# Generated by Django 3.1.7 on 2023-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Supplier_Order_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sompoitem',
            name='supp_product_id',
        ),
        migrations.AddField(
            model_name='sompoheader',
            name='invoicing_detail',
            field=models.CharField(blank=True, db_column='INVOICING_DETAIL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sompoheader',
            name='pdf_invoice_address',
            field=models.CharField(blank=True, db_column='PDF_INVOICE_ADDRESS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sompoheader',
            name='requester_company_name',
            field=models.CharField(blank=True, db_column='REQUESTER_COMPANY_NAME', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sompoheader',
            name='requester_email',
            field=models.CharField(blank=True, db_column='REQUESTER_EMAIL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sompoheader',
            name='requester_fax_no',
            field=models.CharField(blank=True, db_column='REQUESTER_FAX_NO', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sompoheader',
            name='requester_mobile_num',
            field=models.CharField(blank=True, db_column='REQUESTER_MOBILE_NUM', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sompoheader',
            name='supplier_contact',
            field=models.CharField(db_column='SUPPLIER_CONTACT', max_length=100, null=True, verbose_name='supplier contact name'),
        ),
        migrations.AddField(
            model_name='sompoitem',
            name='supplier_product_id',
            field=models.CharField(blank=True, db_column='SUPPLIER_PRODUCT_ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='someformfielddata',
            name='eform_type',
            field=models.CharField(db_column='EFORM_TYPE', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sompoheader',
            name='goods_recep',
            field=models.CharField(blank=True, db_column='GOODS_RECEP', max_length=50, null=True, verbose_name='Goods Recipient'),
        ),
        migrations.AlterField(
            model_name='sompoheader',
            name='incoterm',
            field=models.CharField(blank=True, db_column='INCOTERM', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sompoheader',
            name='payment_term',
            field=models.CharField(blank=True, db_column='PAYMENT_TERM', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sompoheader',
            name='requester',
            field=models.CharField(db_column='REQUESTER', max_length=50, verbose_name='Requester'),
        ),
        migrations.AlterField(
            model_name='sompoitem',
            name='int_product_id',
            field=models.CharField(db_column='INT_PRODUCT_ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='somsuppliermaster',
            name='email',
            field=models.EmailField(db_column='EMAIL', max_length=100, null=True),
        ),
    ]
