# Generated by Django 3.1.7 on 2023-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Supplier_Order_Management', '0002_auto_20230417_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='sompoitem',
            name='value',
            field=models.DecimalField(blank=True, db_column='VALUE', decimal_places=2, max_digits=15, null=True, verbose_name='Value'),
        ),
    ]
