# Generated by Django 3.1.7 on 2023-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Supplier_Order_Management', '0003_sompoitem_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='someformfielddata',
            name='eform_description',
            field=models.CharField(blank=True, db_column='EFORM_DESCRIPTION', max_length=400, null=True),
        ),
    ]
