# Generated by Django 3.1.7 on 2023-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Time_Sheet', '0002_auto_20230104_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectefforts',
            name='effort_day',
            field=models.CharField(blank=True, db_column='EFFORT_DAY', max_length=10, null=True),
        ),
    ]
