# Generated by Django 3.1.7 on 2023-07-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0002_auto_20230626_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoGroupCriteria',
            fields=[
                ('po_group_criteria_guid', models.CharField(db_column='PO_GROUP_CRITERIA_GUID', max_length=32, primary_key=True, serialize=False)),
                ('company_code_id', models.CharField(db_column='COMPANY_CODE_ID', max_length=20)),
                ('activate', models.BooleanField(db_column='ACTIVATE', default=False)),
                ('del_ind', models.BooleanField(default=False)),
                ('po_group_criteria_created_by', models.CharField(db_column='PO_GROUP_CRITERIA_CREATED_BY', max_length=30, null=True)),
                ('po_group_criteria_created_at', models.DateTimeField(db_column='PO_GROUP_CRITERIA_CREATED_AT', max_length=50, null=True)),
                ('po_group_criteria_changed_by', models.CharField(db_column='PO_GROUP_CRITERIA_CHANGED_BY', max_length=30, null=True)),
                ('po_group_criteria_changed_at', models.DateTimeField(db_column='PO_GROUP_CRITERIA_CHANGED_AT', max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
                ('po_split_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.posplittype')),
            ],
            options={
                'db_table': 'MAD_PO_GROUP_CRITERIA',
                'managed': True,
            },
        ),
    ]
