# Generated by Django 3.1.7 on 2022-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0003_auto_20220606_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesiddesc',
            name='messages_category',
            field=models.CharField(blank=True, db_column='MESSAGES_CATEGORY', max_length=1, null=True),
        ),
    ]
