# Generated by Django 3.1.7 on 2023-07-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0003_pogroupcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoSplitGroupType_Temp',
            fields=[
                ('po_split_group_type', models.PositiveIntegerField(db_column='PO_SPLIT_GROUP_TYPE', primary_key=True, serialize=False)),
                ('po_split_group_type_desc', models.CharField(db_column='PO_SPLIT_GROUP_TYPE_DESC', max_length=30)),
                ('po_split_group_type_created_by', models.CharField(db_column='PO_SPLIT_GROUP_TYPE_CREATED_BY', max_length=30, null=True)),
                ('po_split_group_type_created_at', models.DateTimeField(db_column='PO_SPLIT_GROUP_TYPE_CREATED_AT', max_length=50, null=True)),
                ('po_split_group_type_changed_by', models.CharField(db_column='PO_SPLIT_GROUP_TYPE_CHANGED_BY', max_length=30, null=True)),
                ('po_split_group_type_changed_at', models.DateTimeField(db_column='PO_SPLIT_GROUP_TYPE_CHANGED_AT', max_length=50, null=True)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'MAD_SPLIT_GROUP_TYPE_TEMP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PoGroupCriteria_Temp',
            fields=[
                ('po_group_criteria_guid', models.CharField(db_column='PO_GROUP_CRITERIA_GUID', max_length=32, primary_key=True, serialize=False)),
                ('company_code_id', models.CharField(db_column='COMPANY_CODE_ID', max_length=20)),
                ('activate', models.BooleanField(db_column='ACTIVATE', default=False)),
                ('del_ind', models.BooleanField(default=False)),
                ('po_group_criteria_created_by', models.CharField(db_column='PO_GROUP_CRITERIA_CREATED_BY', max_length=30, null=True)),
                ('po_group_criteria_created_at', models.DateTimeField(db_column='PO_GROUP_CRITERIA_CREATED_AT', max_length=50, null=True)),
                ('po_group_criteria_changed_by', models.CharField(db_column='PO_GROUP_CRITERIA_CHANGED_BY', max_length=30, null=True)),
                ('po_group_criteria_changed_at', models.DateTimeField(db_column='PO_GROUP_CRITERIA_CHANGED_AT', max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
                ('po_split_group_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.posplitgrouptype_temp')),
            ],
            options={
                'db_table': 'MAD_PO_GROUP_CRITERIA_TEMP',
                'managed': True,
            },
        ),
    ]
