# Generated by Django 3.1.7 on 2023-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0004_pogroupcriteria_temp_posplitgrouptype_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontrol',
            name='prod_cat_id',
            field=models.CharField(db_column='PROD_CAT_ID', default=None, max_length=50),
        ),
    ]
