# Generated by Django 3.1.7 on 2022-06-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0004_messagesiddesc_messages_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posplitcriteria',
            name='po_split_criteria_changed_at',
            field=models.DateTimeField(db_column='PO_SPLIT_CRITERIA_CHANGED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posplitcriteria',
            name='po_split_criteria_changed_by',
            field=models.CharField(db_column='PO_SPLIT_CRITERIA_CHANGED_BY', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='posplitcriteria',
            name='po_split_criteria_created_at',
            field=models.DateTimeField(db_column='PO_SPLIT_CRITERIA_CREATED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posplitcriteria',
            name='po_split_criteria_created_by',
            field=models.CharField(db_column='PO_SPLIT_CRITERIA_CREATED_BY', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='posplittype',
            name='po_split_type_changed_at',
            field=models.DateTimeField(db_column='PO_SPLIT_TYPE_CHANGED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posplittype',
            name='po_split_type_changed_by',
            field=models.CharField(db_column='PO_SPLIT_TYPE_CHANGED_BY', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='posplittype',
            name='po_split_type_created_at',
            field=models.DateTimeField(db_column='PO_SPLIT_TYPE_CREATED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posplittype',
            name='po_split_type_created_by',
            field=models.CharField(db_column='PO_SPLIT_TYPE_CREATED_BY', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orgaddress',
            name='email',
            field=models.EmailField(db_column='EMAIL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgaddress',
            name='fax_number',
            field=models.CharField(db_column='FAX_NUMBER', max_length=30, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='orgaddress',
            name='telephone_number',
            field=models.CharField(blank=True, db_column='TELEPHONE_NUMBER', max_length=20, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='orgaddress',
            name='title',
            field=models.CharField(db_column='TITLE', max_length=40, null=True),
        ),
    ]
