# Generated by Django 3.1.7 on 2023-09-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0004_auto_20230922_1309'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountassignmentcategory',
            table='MDD_ACC_AST_CAT',
        ),
    ]
