# Generated by Django 3.1.7 on 2022-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0005_auto_20220620_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='posplittype',
            name='del_ind',
            field=models.BooleanField(default=False),
        ),
    ]
