# Generated by Django 3.1.7 on 2023-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0005_purchasecontrol_prod_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrule',
            name='prod_cat_id_from',
            field=models.IntegerField(db_column='PROD_CAT_ID_FROM', max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcingrule',
            name='prod_cat_id_to',
            field=models.IntegerField(db_column='PROD_CAT_ID_TO', max_length=20),
        ),
    ]
