# Generated by Django 3.1.7 on 2022-09-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0006_posplittype_del_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypeDescription',
            fields=[
                ('field_type_description_guid', models.CharField(db_column='FIELD_TYPE_DESCRIPTION_GUID', max_length=32, primary_key=True, serialize=False)),
                ('field_type_id', models.CharField(db_column='FIELD_TYPE_ID', max_length=30)),
                ('field_type_desc', models.CharField(db_column='FIELD_TYPE_DESC', max_length=30)),
                ('used_flag', models.BooleanField(db_column='USED_FLAG', default=False)),
                ('field_type_desc_created_by', models.CharField(db_column='FIELD_TYPE_DESC_CREATED_BY', max_length=30, null=True)),
                ('field_type_desc_created_at', models.DateTimeField(db_column='FIELD_TYPE_DESC_CREATED_AT', max_length=50, null=True)),
                ('field_type_desc_changed_by', models.CharField(db_column='FIELD_TYPE_DESC_CHANGED_BY', max_length=30, null=True)),
                ('field_type_desc_changed_at', models.DateTimeField(db_column='FIELD_TYPE_DESC_CHANGED_AT', max_length=50, null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
                ('field_name', models.ForeignKey(db_column='FIELD_NAME', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.fielddesc')),
            ],
            options={
                'db_table': 'MDD_FIELD_TYPE_DESCRIPTION',
                'managed': True,
            },
        ),
    ]
