# Generated by Django 3.1.7 on 2022-09-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0007_fieldtypedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseControl',
            fields=[
                ('purchase_control_guid', models.CharField(db_column='PURCHASE_CONTROL_GUID', max_length=32, primary_key=True, serialize=False)),
                ('company_code_id', models.CharField(db_column='COMPANY_CODE_ID', max_length=20)),
                ('purchase_ctrl_flag', models.BooleanField(db_column='PURCHASE_CTRL_FLAG', default=False)),
                ('del_ind', models.BooleanField(default=False)),
                ('purchase_control_created_by', models.CharField(db_column='PURCHASE_CONTROL_CREATED_BY', max_length=30, null=True)),
                ('purchase_control_created_at', models.DateTimeField(db_column='PURCHASE_CONTROL_CREATED_AT', max_length=50, null=True)),
                ('purchase_control_changed_by', models.CharField(db_column='PURCHASE_CONTROL_CHANGED_BY', max_length=30, null=True)),
                ('purchase_control_changed_at', models.DateTimeField(db_column='PURCHASE_CONTROL_CHANGED_AT', max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MAD_PURCHASE_CONTROL',
                'managed': True,
            },
        ),
    ]
