# Generated by Django 3.1.7 on 2022-09-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0008_purchasecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontrol',
            name='call_off',
            field=models.CharField(db_column='CALL_OFF', max_length=15, null=True),
        ),
    ]
