# Generated by Django 3.1.7 on 2022-10-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0009_purchasecontrol_call_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdetail',
            name='discount_id',
            field=models.CharField(db_column='DISCOUNT_ID', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productsdetail',
            name='variant_id',
            field=models.CharField(db_column='VARIANT_ID', max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='DiscountData',
            fields=[
                ('discount_data_guid', models.CharField(db_column='DISCOUNT_DATA_GUID', max_length=40, primary_key=True, serialize=False)),
                ('discount_id', models.CharField(db_column='DISCOUNT_ID', max_length=40, null=True)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=16, null=True)),
                ('discount_name', models.CharField(db_column='DISCOUNT_NAME', max_length=500, null=True)),
                ('quantity', models.CharField(db_column='quantity', max_length=30, null=True)),
                ('discount_percentage', models.DecimalField(db_column='DISCOUNT_PERCENTAGE', decimal_places=2, max_digits=15, null=True)),
                ('discount_data_created_at', models.DateTimeField(db_column='DISCOUNT_DATA_CREATED_AT', null=True)),
                ('discount_data_created_by', models.CharField(db_column='DISCOUNT_DATA_CREATED_BY', max_length=12, null=True)),
                ('discount_data_changed_at', models.DateTimeField(blank=True, db_column='DISCOUNT_DATA_CHANGED_AT', null=True)),
                ('discount_data_changed_by', models.CharField(db_column='DISCOUNT_DATA_CHANGED_BY', max_length=12, null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MAD_DISCOUNT_DATA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VariantConfig',
            fields=[
                ('variant_config_guid', models.CharField(db_column='VARIANT_CONFIG_GUID', max_length=40, primary_key=True, serialize=False)),
                ('variant_id', models.CharField(db_column='VARIANT_ID', max_length=40, null=True)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=16, null=True)),
                ('variant_count', models.PositiveIntegerField(db_column='VARIANT_COUNT', default=0, verbose_name='field count')),
                ('variant_name', models.CharField(db_column='VARIANT_NAME', max_length=200, null=True)),
                ('variant_datatype', models.CharField(db_column='VARIANT_DATATYPE', max_length=50, null=True)),
                ('variant_data', models.CharField(db_column='VARIANT_DATA', max_length=1000, null=True)),
                ('default_variant_data', models.CharField(db_column='DEFAULT_VARIANT_DATA', max_length=100, null=True)),
                ('required_flag', models.BooleanField(db_column='REQUIRED_FLAG', null=True)),
                ('specialchar_flag', models.BooleanField(db_column='SPECIALCHAR_FLAG', null=True)),
                ('display_flag', models.BooleanField(db_column='DISPLAY_FLAG', default=False, null=True)),
                ('dropdown_pricetype', models.CharField(db_column='DROPDOWN_PRICETYPE', max_length=50, null=True)),
                ('variant_flag', models.BooleanField(db_column='VARIANT_FLAG', default=False, null=True)),
                ('variant_config_created_at', models.DateTimeField(db_column='VARIANT_CONFIG_CREATED_AT', null=True)),
                ('variant_config_created_by', models.CharField(db_column='VARIANT_CONFIG_CREATED_BY', max_length=12, null=True)),
                ('variant_config_changed_at', models.DateTimeField(blank=True, db_column='VARIANT_CONFIG_CHANGED_AT', null=True)),
                ('variant_config_changed_by', models.CharField(db_column='VARIANT_CONFIG_CHANGED_BY', max_length=12, null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MAD_VARIANT_CONFIG',
                'unique_together': {('client', 'variant_id', 'variant_count')},
            },
        ),
    ]
