# Generated by Django 3.1.7 on 2022-11-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0011_producteformpricing_variant_config_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverLimit_h',
            fields=[
                ('app_guid', models.CharField(db_column='APP_GUID', max_length=32, primary_key=True, serialize=False)),
                ('approver_username', models.CharField(db_column='APPROVER_USERNAME', max_length=16)),
                ('app_code_id', models.CharField(db_column='APP_CODE_ID', max_length=8)),
                ('company_id', models.CharField(db_column='COMPANY_ID', max_length=8)),
                ('approver_limit_created_by', models.CharField(db_column='APPROVER_LIMIT_CREATED_BY', max_length=30, null=True)),
                ('approver_limit_created_at', models.DateTimeField(db_column='APPROVER_LIMIT_CREATED_AT', max_length=50, null=True)),
                ('approver_limit_changed_by', models.CharField(db_column='APPROVER_LIMIT_CHANGED_BY', max_length=30, null=True)),
                ('approver_limit_changed_at', models.DateTimeField(db_column='APPROVER_LIMIT_CHANGED_AT', max_length=50, null=True)),
                ('approver_limit_source_system', models.CharField(db_column='APPROVER_LIMIT_SOURCE_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MMD_APPROVER_LIMIT_ID_H',
                'managed': True,
            },
        ),
    ]
