# Generated by Django 3.1.7 on 2022-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0011_producteformpricing_variant_config_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_id',
            field=models.CharField(db_column='PRODUCT_ID', max_length=16, null=True),
        ),
    ]
