# Generated by Django 3.1.7 on 2022-11-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0012_productinfo_product_id'),
        ('eProc_Configuration', '0012_approverlimit_h'),
    ]

    operations = [
    ]
