# Generated by Django 3.1.7 on 2022-12-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0014_accountingdatadeschistory_accountingdatahistory_approverlimithistory_approverlimitvaluehistory_deter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgpgroup',
            name='porg_id',
            field=models.CharField(db_column='PORG_ID', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='orgpgrouphistory',
            name='porg_id',
            field=models.CharField(db_column='PORG_ID', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='orgporg',
            name='company_id',
            field=models.CharField(db_column='COMPANY_ID', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='orgporghistory',
            name='company_id',
            field=models.CharField(db_column='COMPANY_ID', max_length=8, null=True),
        ),
    ]
