# Generated by Django 3.1.7 on 2022-12-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0016_projectcategories_projectdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategoriesMapping',
            fields=[
                ('project_categories_mapping_guid', models.CharField(db_column='PROJECT_CATEGORIES_MAPPING_GUID', max_length=32, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_column='PROJECT_ID', max_length=20)),
                ('project_category_id', models.CharField(db_column='PROJECT_CATEGORY_ID', max_length=255)),
                ('client', models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MAD_PROJECT_CATEGORIES_MAPPING',
                'managed': True,
                'unique_together': {('client', 'project_category_id', 'project_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectsCategories',
            fields=[
                ('project_categories_guid', models.CharField(db_column='PROJECT_CATEGORIES_GUID', max_length=32, primary_key=True, serialize=False)),
                ('project_category_id', models.CharField(db_column='PROJECT_CATEGORY_ID', max_length=255)),
                ('project_category_description', models.CharField(db_column='PROJECT_CATEGORY_DESCRIPTION', max_length=255)),
                ('projects_categories_created_by', models.CharField(db_column='PROJECTS_CATEGORIES_CREATED_BY', max_length=30, null=True)),
                ('projects_categories_created_at', models.DateTimeField(db_column='PROJECTS_CATEGORIES_CREATED_AT', max_length=50, null=True)),
                ('projects_categories_changed_by', models.CharField(db_column='PROJECTS_CATEGORIES_CHANGED_BY', max_length=30, null=True)),
                ('projects_categories_changed_at', models.DateTimeField(db_column='PROJECTS_CATEGORIES_CHANGED_AT', max_length=50, null=True)),
                ('client', models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MAD_PROJECTS_CATEGORIES',
                'managed': True,
                'unique_together': {('client', 'project_category_id')},
            },
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_details_changed_at',
            field=models.DateTimeField(db_column='PROJECT_DETAILS_CHANGED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_details_changed_by',
            field=models.CharField(db_column='PROJECT_DETAILS_CHANGED_BY', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_details_created_at',
            field=models.DateTimeField(db_column='PROJECT_DETAILS_CREATED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_details_created_by',
            field=models.CharField(db_column='PROJECT_DETAILS_CREATED_BY', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectCategories',
        ),
    ]
