# Generated by Django 3.1.7 on 2022-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0017_auto_20221214_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategoriesmapping',
            name='project_categories_mapping_changed_at',
            field=models.DateTimeField(db_column='PROJECT_CATEGORIES_MAPPING_CHANGED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectcategoriesmapping',
            name='project_categories_mapping_changed_by',
            field=models.CharField(db_column='PROJECT_CATEGORIES_MAPPING_CHANGED_BY', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectcategoriesmapping',
            name='project_categories_mapping_created_at',
            field=models.DateTimeField(db_column='PROJECT_CATEGORIES_MAPPING_CREATED_AT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectcategoriesmapping',
            name='project_categories_mapping_created_by',
            field=models.CharField(db_column='PROJECT_CATEGORIES_MAPPING_CREATED_BY', max_length=30, null=True),
        ),
    ]
