# Generated by Django 3.1.7 on 2023-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0018_auto_20221214_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategoriesmapping',
            name='del_ind',
            field=models.BooleanField(db_column='DEL_IND', default=False),
        ),
        migrations.AddField(
            model_name='projectscategories',
            name='del_ind',
            field=models.BooleanField(db_column='DEL_IND', default=False),
        ),
    ]
