# Generated by Django 3.1.7 on 2023-06-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0019_auto_20230104_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPorgMapping',
            fields=[
                ('org_porg_mapping_guid', models.CharField(db_column='ORG_PORG_MAPPING_GUID', max_length=32, primary_key=True, serialize=False)),
                ('porg_id', models.CharField(db_column='PORG_ID', max_length=8)),
                ('company_id', models.CharField(db_column='COMPANY_ID', max_length=8, null=True)),
                ('org_porg_mapping_created_by', models.CharField(db_column='ORG_PORG_MAPPING_CREATED_BY', max_length=30, null=True)),
                ('org_porg_mapping_created_at', models.DateTimeField(db_column='ORG_PORG_MAPPING_CREATED_AT', max_length=50, null=True)),
                ('org_porg_mapping_changed_by', models.CharField(db_column='ORG_PORG_MAPPING_CHANGED_BY', max_length=30, null=True)),
                ('org_porg_mapping_changed_at', models.DateTimeField(db_column='ORG_PORG_MAPPING_CHANGED_AT', max_length=50, null=True)),
                ('org_porg_mapping_source_system', models.CharField(db_column='ORG_PORG_MAPPING_SOURCE_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MMD_ORG_PORG_MAPPING',
                'managed': True,
            },
        ),
    ]
