# Generated by Django 3.1.7 on 2023-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0021_orgporgmapping_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgCompaniesH',
            fields=[
                ('company_key', models.AutoField(db_column='COMPANY_KEY', primary_key=True, serialize=False)),
                ('company_guid', models.CharField(db_column='COMPANY_GUID', max_length=32)),
                ('name1', models.CharField(db_column='NAME1', max_length=100)),
                ('name2', models.CharField(db_column='NAME2', max_length=100)),
                ('company_id', models.CharField(db_column='COMPANY_ID', max_length=8)),
                ('org_companies_created_by', models.CharField(db_column='ORG_COMPANIES_CREATED_BY', max_length=30, null=True)),
                ('org_companies_created_at', models.DateTimeField(db_column='ORG_COMPANIES_CREATED_AT', max_length=50, null=True)),
                ('org_companies_changed_by', models.CharField(db_column='ORG_COMPANIES_CHANGED_BY', max_length=30, null=True)),
                ('org_companies_changed_at', models.DateTimeField(db_column='ORG_COMPANIES_CHANGED_AT', max_length=50, null=True)),
                ('org_companies_source_system', models.CharField(db_column='ORG_COMPANIES_SOURCE_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.CharField(db_column='CLIENT', max_length=8, null=True)),
                ('object_id', models.PositiveBigIntegerField(db_column='OBJECT_ID', null=True)),
            ],
            options={
                'db_table': 'MMD_ORG_COMPANIES_H',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgPGroupH',
            fields=[
                ('pgroup_key', models.AutoField(db_column='PGROUP_KEY', primary_key=True, serialize=False)),
                ('pgroup_guid', models.CharField(db_column='PGROUP_GUID', max_length=32)),
                ('pgroup_id', models.CharField(db_column='PGROUP_ID', max_length=8)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=100)),
                ('porg_id', models.CharField(db_column='PORG_ID', max_length=8, null=True)),
                ('org_pgroup_created_by', models.CharField(db_column='ORG_PGROUP_CREATED_BY', max_length=30, null=True)),
                ('org_pgroup_created_at', models.DateTimeField(db_column='ORG_PGROUP_CREATED_AT', max_length=50, null=True)),
                ('org_pgroup_changed_by', models.CharField(db_column='ORG_PGROUP_CHANGED_BY', max_length=30, null=True)),
                ('org_pgroup_changed_at', models.DateTimeField(db_column='ORG_PGROUP_CHANGED_AT', max_length=50, null=True)),
                ('org_pgroup_source_system', models.CharField(db_column='ORG_PGROUP_SOURCE_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.CharField(db_column='CLIENT', max_length=8, null=True)),
                ('object_id', models.PositiveBigIntegerField(db_column='OBJECT_ID', null=True)),
            ],
            options={
                'db_table': 'MMD_ORG_PGROUP_H',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgPorgH',
            fields=[
                ('porg_key', models.AutoField(db_column='PORG_KEY', primary_key=True, serialize=False)),
                ('porg_guid', models.CharField(db_column='PORG_GUID', max_length=32)),
                ('porg_id', models.CharField(db_column='PORG_ID', max_length=8)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=100)),
                ('company_id', models.CharField(db_column='COMPANY_ID', max_length=8, null=True)),
                ('org_porg_created_by', models.CharField(db_column='ORG_PORG_CREATED_BY', max_length=30, null=True)),
                ('org_porg_created_at', models.DateTimeField(db_column='ORG_PORG_CREATED_AT', max_length=50, null=True)),
                ('org_porg_changed_by', models.CharField(db_column='ORG_PORG_CHANGED_BY', max_length=30, null=True)),
                ('org_porg_changed_at', models.DateTimeField(db_column='ORG_PORG_CHANGED_AT', max_length=50, null=True)),
                ('org_porg_source_system', models.CharField(db_column='ORG_PORG_SOURCE_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.CharField(db_column='CLIENT', max_length=8, null=True)),
                ('object_id', models.PositiveBigIntegerField(db_column='OBJECT_ID', null=True)),
            ],
            options={
                'db_table': 'MMD_ORG_PORG_H',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='orgpgrouphistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orgpgrouphistory',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='orgporghistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orgporghistory',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='OrgCompaniesHistory',
        ),
        migrations.DeleteModel(
            name='OrgPGroupHistory',
        ),
        migrations.DeleteModel(
            name='OrgPorgHistory',
        ),
    ]
