# Generated by Django 3.1.7 on 2023-06-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0022_auto_20230619_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRule',
            fields=[
                ('sourcing_rule_guid', models.CharField(db_column='SOURCING_RULE_GUID', default=None, max_length=32, primary_key=True, serialize=False)),
                ('prod_cat_id_from', models.CharField(db_column='PROD_CAT_ID_FROM', max_length=20)),
                ('prod_cat_id_to', models.CharField(db_column='PROD_CAT_ID_TO', max_length=20)),
                ('sourcing_flag', models.BooleanField(db_column='SOURCING_FLAG', default=False)),
                ('call_off', models.CharField(db_column='CALL_OFF', max_length=15, null=True)),
                ('sourcing_rule_source_system', models.CharField(db_column='SOURCING_RULE_SOURCE_SYSTEM', max_length=20)),
                ('sourcing_rule_created_by', models.CharField(db_column='SOURCING_RULE_CREATED_BY', max_length=30, null=True)),
                ('sourcing_rule_created_at', models.DateTimeField(db_column='SOURCING_RULE_CREATED_AT', max_length=50, null=True)),
                ('sourcing_rule_changed_by', models.CharField(db_column='SOURCING_RULE_CHANGED_BY', max_length=30, null=True)),
                ('sourcing_rule_changed_at', models.DateTimeField(db_column='SOURCING_RULE_CHANGED_AT', max_length=50, null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MAD_SOURCING_RULE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SourcingMapping',
            fields=[
                ('sourcing_mapping_guid', models.CharField(db_column='SOURCING_MAPPING_GUID', default=None, max_length=32, primary_key=True, serialize=False)),
                ('prod_cat_id', models.CharField(db_column='PROD_CAT_ID', max_length=20)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=16, null=True)),
                ('company_id', models.CharField(db_column='COMPANY_ID', max_length=8)),
                ('sourcing_mapping_source_system', models.CharField(db_column='SOURCING_MAPPING_SOURCE_SYSTEM', max_length=20)),
                ('sourcing_mapping_created_by', models.CharField(db_column='SOURCING_MAPPING_CREATED_BY', max_length=30, null=True)),
                ('sourcing_mapping_created_at', models.DateTimeField(db_column='SOURCING_MAPPING_CREATED_AT', max_length=50, null=True)),
                ('sourcing_mapping_changed_by', models.CharField(db_column='SOURCING_MAPPING_CHANGED_BY', max_length=30, null=True)),
                ('sourcing_mapping_changed_at', models.DateTimeField(db_column='SOURCING_MAPPING_CHANGED_AT', max_length=50, null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MAD_SOURCING_MAPPING',
                'managed': True,
            },
        ),
    ]
