# Generated by Django 3.1.7 on 2023-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0023_sourcingmapping_sourcingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrule',
            name='company_id',
            field=models.CharField(db_column='COMPANY_ID', max_length=8, null=True),
        ),
    ]
