# Generated by Django 3.1.7 on 2023-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0024_sourcingrule_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingmapping',
            name='rule_type',
            field=models.CharField(db_column='RULE_TYPE', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sourcingrule',
            name='rule_type',
            field=models.CharField(db_column='RULE_TYPE', max_length=3, null=True),
        ),
    ]
