# Generated by Django 3.1.7 on 2022-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Purchase_Order', '0002_auto_20220519_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='manu_name',
        ),
        migrations.AddField(
            model_name='poitem',
            name='manufacturer',
            field=models.CharField(blank=True, db_column='MANUFACTURER', max_length=50, null=True, verbose_name='Manufacturer'),
        ),
    ]
