# Generated by Django 3.1.7 on 2022-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Purchase_Order', '0004_auto_20220531_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitem',
            name='bundle_flag',
            field=models.BooleanField(blank=True, db_column='BUNDLE_FLAG', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='tiered_flag',
            field=models.BooleanField(blank=True, db_column='TIERED_FLAG', default=False, null=True),
        ),
    ]
