# Generated by Django 3.1.7 on 2022-05-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Purchase_Order', '0005_auto_20220531_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitem',
            name='bill_to_addr_num',
            field=models.CharField(blank=True, db_column='BILL_TO_ADDR_NUM', max_length=10, null=True, verbose_name='bill to addr num'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='description',
            field=models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='dis_rej_ind',
            field=models.BooleanField(blank=True, db_column='DIS_REJ_IND', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='final_entry_ind',
            field=models.BooleanField(blank=True, db_column='FINAL_ENTRY_IND', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='final_inv',
            field=models.BooleanField(blank=True, db_column='FINAL_INV', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='goods_recep',
            field=models.CharField(blank=True, db_column='GOODS_RECEP', max_length=12, null=True, verbose_name='Goods Recipient'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='prod_cat_desc',
            field=models.CharField(blank=True, db_column='PROD_CAT_DESC', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='ship_from_addr_num',
            field=models.CharField(blank=True, db_column='SHIP_from_ADDR_NUM', max_length=10, null=True, verbose_name='ship from addr num'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='ship_to_addr_num',
            field=models.CharField(blank=True, db_column='SHIP_TO_ADDR_NUM', max_length=10, null=True, verbose_name='ship to addr num'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='undef_limit',
            field=models.BooleanField(blank=True, db_column='UNDEF_LIMIT', default=False, null=True),
        ),
    ]
