# Generated by Django 3.1.7 on 2022-06-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Purchase_Order', '0006_auto_20220531_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='inv_addr_num',
            field=models.PositiveIntegerField(blank=True, db_column='INV_ADDR_NUM', null=True, verbose_name='Invoice address number'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='ship_addr_num',
            field=models.PositiveIntegerField(blank=True, db_column='SHIP_ADDR_NUM', null=True, verbose_name='Ship to Address Number'),
        ),
    ]
