# Generated by Django 3.1.7 on 2022-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Purchase_Order', '0007_auto_20220602_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='po_pdf_creation_flag',
            field=models.BooleanField(db_column='PO_PDF_CREATION_FLAG', default=False),
        ),
        migrations.AddField(
            model_name='poheader',
            name='po_pdf_email_flag',
            field=models.BooleanField(db_column='PO_PDF_EMAIL_FLAG', default=False),
        ),
    ]
