# Generated by Django 3.1.7 on 2022-06-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Purchase_Order', '0008_auto_20220607_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poaddresses',
            name='title',
            field=models.CharField(db_column='TITLE', max_length=40, null=True),
        ),
    ]
