# Generated by Django 3.1.7 on 2022-08-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Shop_Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritecart',
            name='actual_price',
            field=models.DecimalField(blank=True, db_column='ACTUAL_PRICE', decimal_places=2, max_digits=15, null=True, verbose_name='Price without discount'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='additional_price',
            field=models.DecimalField(blank=True, db_column='ADDITIONAL_PRICE', decimal_places=2, max_digits=15, null=True, verbose_name='additionalprice of the item'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='base_price',
            field=models.DecimalField(blank=True, db_column='BASE_PRICE', decimal_places=2, max_digits=15, null=True, verbose_name='base price of the item'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='cgst',
            field=models.DecimalField(blank=True, db_column='CGST', decimal_places=2, max_digits=15, null=True, verbose_name='Central GST'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='discount_percentage',
            field=models.DecimalField(blank=True, db_column='DISCOUNT_PERCENTAGE', decimal_places=2, max_digits=15, null=True, verbose_name='Discount percentage'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='discount_value',
            field=models.DecimalField(blank=True, db_column='DISCOUNT_VALUE', decimal_places=2, max_digits=15, null=True, verbose_name='Discount value'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='sgst',
            field=models.DecimalField(blank=True, db_column='SGST', decimal_places=2, max_digits=15, null=True, verbose_name='State GST'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='tax_value',
            field=models.DecimalField(blank=True, db_column='TAX_VALUE', decimal_places=2, max_digits=15, null=True, verbose_name='tax Value'),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='vat',
            field=models.DecimalField(blank=True, db_column='VAT', decimal_places=2, max_digits=15, null=True, verbose_name='Value Added Tax - VAT code (%age as decimal) returned from catalogue '),
        ),
    ]
