# Generated by Django 3.1.7 on 2022-10-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Shop_Home', '0002_auto_20220809_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritecart',
            name='discount_id',
            field=models.CharField(db_column='DISCOUNT_ID', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='favouritecart',
            name='variant_id',
            field=models.CharField(db_column='VARIANT_ID', max_length=40, null=True),
        ),
    ]
